"""Plan Comptable Minimum Normalise (PCMN) - Belgique - Copropriete"""

PCMN_ACCOUNTS = [
    # Classe 1 - Capitaux propres
    {"number": "100000", "name": "Capital de la copropriete", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "130000", "name": "Reserves", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "130100", "name": "Reserve ordinaire", "class_num": 1, "parent": "130000", "type": "balance"},
    {"number": "130200", "name": "Reserve extraordinaire", "class_num": 1, "parent": "130000", "type": "balance"},
    {"number": "140000", "name": "Resultat reporte", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "140100", "name": "Benefice reporte", "class_num": 1, "parent": "140000", "type": "balance"},
    {"number": "140200", "name": "Perte reportee", "class_num": 1, "parent": "140000", "type": "balance"},
    {"number": "160000", "name": "Provisions", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "160100", "name": "Provisions pour grosses reparations", "class_num": 1, "parent": "160000", "type": "balance"},
    {"number": "160200", "name": "Provisions pour litiges", "class_num": 1, "parent": "160000", "type": "balance"},
    {"number": "170000", "name": "Dettes a plus d'un an", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "173000", "name": "Emprunts", "class_num": 1, "parent": "170000", "type": "balance"},

    # Classe 2 - Immobilisations
    {"number": "220000", "name": "Terrains et constructions", "class_num": 2, "parent": None, "type": "balance"},
    {"number": "221000", "name": "Terrains", "class_num": 2, "parent": "220000", "type": "balance"},
    {"number": "222000", "name": "Constructions", "class_num": 2, "parent": "220000", "type": "balance"},
    {"number": "230000", "name": "Installations et machines", "class_num": 2, "parent": None, "type": "balance"},
    {"number": "231000", "name": "Ascenseur", "class_num": 2, "parent": "230000", "type": "balance"},
    {"number": "232000", "name": "Chauffage central", "class_num": 2, "parent": "230000", "type": "balance"},
    {"number": "240000", "name": "Mobilier et materiel", "class_num": 2, "parent": None, "type": "balance"},

    # Classe 4 - Creances et dettes
    {"number": "400000", "name": "Proprietaires - Appels de fonds", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "401000", "name": "Proprietaires - Fonds de roulement", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "402000", "name": "Proprietaires - Provisions chauffage", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "403000", "name": "Proprietaires - Provisions eau", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "404000", "name": "Proprietaires - Provisions electricite", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "405000", "name": "Proprietaires - Decomptes", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "410000", "name": "TVA a recuperer", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "411000", "name": "TVA sur achats", "class_num": 4, "parent": "410000", "type": "balance"},
    {"number": "440000", "name": "Fournisseurs", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "441000", "name": "Fournisseurs - Factures a recevoir", "class_num": 4, "parent": "440000", "type": "balance"},
    {"number": "442000", "name": "Fournisseurs - Notes de credit", "class_num": 4, "parent": "440000", "type": "balance"},
    {"number": "450000", "name": "Dettes fiscales", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "451000", "name": "Dettes sociales", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "460000", "name": "Acomptes recus", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "470000", "name": "Dettes diverses", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "480000", "name": "Comptes de regularisation", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "490000", "name": "Comptes d'attente", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "491000", "name": "Compte d'attente - Recettes", "class_num": 4, "parent": "490000", "type": "balance"},
    {"number": "492000", "name": "Compte d'attente - Depenses", "class_num": 4, "parent": "490000", "type": "balance"},

    # Classe 5 - Tresorerie
    {"number": "550000", "name": "Banque - Compte courant", "class_num": 5, "parent": None, "type": "balance"},
    {"number": "550100", "name": "Banque - Compte epargne", "class_num": 5, "parent": None, "type": "balance"},
    {"number": "550200", "name": "Banque - Compte fonds de reserve", "class_num": 5, "parent": None, "type": "balance"},
    {"number": "570000", "name": "Caisse", "class_num": 5, "parent": None, "type": "balance"},

    # Classe 6 - Charges
    {"number": "600000", "name": "Achats de fournitures", "class_num": 6, "parent": None, "type": "result"},
    {"number": "601000", "name": "Fournitures d'entretien", "class_num": 6, "parent": "600000", "type": "result"},
    {"number": "602000", "name": "Fournitures de bureau", "class_num": 6, "parent": "600000", "type": "result"},
    {"number": "610000", "name": "Services et biens divers", "class_num": 6, "parent": None, "type": "result"},
    {"number": "611000", "name": "Entretien et reparations", "class_num": 6, "parent": "610000", "type": "result"},
    {"number": "611100", "name": "Entretien espaces communs", "class_num": 6, "parent": "611000", "type": "result"},
    {"number": "611200", "name": "Entretien ascenseur", "class_num": 6, "parent": "611000", "type": "result"},
    {"number": "611300", "name": "Entretien chauffage", "class_num": 6, "parent": "611000", "type": "result"},
    {"number": "611400", "name": "Entretien toiture", "class_num": 6, "parent": "611000", "type": "result"},
    {"number": "611500", "name": "Entretien facade", "class_num": 6, "parent": "611000", "type": "result"},
    {"number": "612000", "name": "Energie", "class_num": 6, "parent": "610000", "type": "result"},
    {"number": "612100", "name": "Electricite parties communes", "class_num": 6, "parent": "612000", "type": "result"},
    {"number": "612200", "name": "Chauffage commun", "class_num": 6, "parent": "612000", "type": "result"},
    {"number": "612300", "name": "Eau", "class_num": 6, "parent": "612000", "type": "result"},
    {"number": "612400", "name": "Gaz", "class_num": 6, "parent": "612000", "type": "result"},
    {"number": "613000", "name": "Assurances", "class_num": 6, "parent": "610000", "type": "result"},
    {"number": "613100", "name": "Assurance incendie", "class_num": 6, "parent": "613000", "type": "result"},
    {"number": "613200", "name": "Assurance responsabilite civile", "class_num": 6, "parent": "613000", "type": "result"},
    {"number": "613300", "name": "Assurance degats des eaux", "class_num": 6, "parent": "613000", "type": "result"},
    {"number": "614000", "name": "Honoraires syndic", "class_num": 6, "parent": "610000", "type": "result"},
    {"number": "615000", "name": "Frais de gestion", "class_num": 6, "parent": "610000", "type": "result"},
    {"number": "615100", "name": "Frais de correspondance", "class_num": 6, "parent": "615000", "type": "result"},
    {"number": "615200", "name": "Frais de reunion AG", "class_num": 6, "parent": "615000", "type": "result"},
    {"number": "616000", "name": "Frais juridiques", "class_num": 6, "parent": "610000", "type": "result"},
    {"number": "617000", "name": "Nettoyage", "class_num": 6, "parent": "610000", "type": "result"},
    {"number": "618000", "name": "Jardinage et espaces verts", "class_num": 6, "parent": "610000", "type": "result"},
    {"number": "619000", "name": "Divers services", "class_num": 6, "parent": "610000", "type": "result"},
    {"number": "620000", "name": "Remunerations", "class_num": 6, "parent": None, "type": "result"},
    {"number": "621000", "name": "Concierge - Remuneration", "class_num": 6, "parent": "620000", "type": "result"},
    {"number": "622000", "name": "Concierge - Charges sociales", "class_num": 6, "parent": "620000", "type": "result"},
    {"number": "630000", "name": "Amortissements", "class_num": 6, "parent": None, "type": "result"},
    {"number": "631000", "name": "Amortissement constructions", "class_num": 6, "parent": "630000", "type": "result"},
    {"number": "632000", "name": "Amortissement installations", "class_num": 6, "parent": "630000", "type": "result"},
    {"number": "640000", "name": "Autres charges d'exploitation", "class_num": 6, "parent": None, "type": "result"},
    {"number": "641000", "name": "Taxes communales", "class_num": 6, "parent": "640000", "type": "result"},
    {"number": "642000", "name": "Precompte immobilier", "class_num": 6, "parent": "640000", "type": "result"},
    {"number": "650000", "name": "Charges financieres", "class_num": 6, "parent": None, "type": "result"},
    {"number": "651000", "name": "Interets sur emprunts", "class_num": 6, "parent": "650000", "type": "result"},
    {"number": "652000", "name": "Frais bancaires", "class_num": 6, "parent": "650000", "type": "result"},
    {"number": "660000", "name": "Charges exceptionnelles", "class_num": 6, "parent": None, "type": "result"},

    # Classe 7 - Produits
    {"number": "700000", "name": "Provisions pour charges communes", "class_num": 7, "parent": None, "type": "result"},
    {"number": "701000", "name": "Provisions fonds de reserve", "class_num": 7, "parent": None, "type": "result"},
    {"number": "702000", "name": "Provisions charges chauffage", "class_num": 7, "parent": None, "type": "result"},
    {"number": "703000", "name": "Provisions charges eau", "class_num": 7, "parent": None, "type": "result"},
    {"number": "704000", "name": "Provisions charges electricite", "class_num": 7, "parent": None, "type": "result"},
    {"number": "710000", "name": "Rappels de charges", "class_num": 7, "parent": None, "type": "result"},
    {"number": "720000", "name": "Indemnites d'assurance", "class_num": 7, "parent": None, "type": "result"},
    {"number": "730000", "name": "Produits divers", "class_num": 7, "parent": None, "type": "result"},
    {"number": "731000", "name": "Location salles communes", "class_num": 7, "parent": "730000", "type": "result"},
    {"number": "732000", "name": "Location parking", "class_num": 7, "parent": "730000", "type": "result"},
    {"number": "750000", "name": "Produits financiers", "class_num": 7, "parent": None, "type": "result"},
    {"number": "751000", "name": "Interets crediteurs", "class_num": 7, "parent": "750000", "type": "result"},
    {"number": "760000", "name": "Produits exceptionnels", "class_num": 7, "parent": None, "type": "result"},
]
