"""Plan Comptable Belge - Copropriete (PCMN officiel pour ACP).

Source: utilisateur final - 327 comptes structures (classes 1-7).
Classes 1-5 = bilan, 6-7 = compte de resultat.
"""

PCMN_ACCOUNTS = [
    # Classe 1 - Capitaux propres et dettes a long terme
    {"number": "10", "name": "Fonds de roulement", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "100", "name": "Fonds de roulement général", "class_num": 1, "parent": "10", "type": "balance"},
    {"number": "12", "name": "Solde en attente sur travaux", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "14", "name": "Résultat exercice", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "16", "name": "Fonds de réserve", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "160", "name": "Fonds de réserve général", "class_num": 1, "parent": "16", "type": "balance"},
    {"number": "160010", "name": "Fond de réserve part occupants", "class_num": 1, "parent": "160", "type": "balance"},
    {"number": "160020", "name": "Indeminté déménagement/emménagement", "class_num": 1, "parent": "160", "type": "balance"},
    {"number": "161", "name": "Fonds de réserve particulier", "class_num": 1, "parent": "16", "type": "balance"},
    {"number": "17", "name": "Dettes à plus d'un an", "class_num": 1, "parent": None, "type": "balance"},
    {"number": "170", "name": "Emprunts subordonnés", "class_num": 1, "parent": "17", "type": "balance"},
    {"number": "171", "name": "Emprunts obligataires non subordonnés", "class_num": 1, "parent": "17", "type": "balance"},
    {"number": "172", "name": "Dettes de location-financement", "class_num": 1, "parent": "17", "type": "balance"},
    {"number": "173", "name": "Etablissements de crédit", "class_num": 1, "parent": "17", "type": "balance"},
    {"number": "1730", "name": "Dettes en compte", "class_num": 1, "parent": "173", "type": "balance"},
    {"number": "1731", "name": "Promesses", "class_num": 1, "parent": "173", "type": "balance"},
    {"number": "1732", "name": "Crédits d'acceptation", "class_num": 1, "parent": "173", "type": "balance"},
    {"number": "174", "name": "Autres emprunts", "class_num": 1, "parent": "17", "type": "balance"},
    {"number": "175", "name": "Dettes commerciales", "class_num": 1, "parent": "17", "type": "balance"},
    {"number": "179", "name": "Dettes diverses", "class_num": 1, "parent": "17", "type": "balance"},
    # Classe 2 - Immobilisations
    {"number": "21", "name": "Immobilisation incorporelles", "class_num": 2, "parent": None, "type": "balance"},
    {"number": "211", "name": "Concessions, brevets, licences, savoir-faire, marques et droits similaires", "class_num": 2, "parent": "21", "type": "balance"},
    {"number": "213", "name": "Acomptes versés", "class_num": 2, "parent": "21", "type": "balance"},
    {"number": "23", "name": "Installations, machines et outillage", "class_num": 2, "parent": None, "type": "balance"},
    {"number": "24", "name": "Mobilier et matériel roulant", "class_num": 2, "parent": None, "type": "balance"},
    {"number": "25", "name": "Immobilisations détenues en location-financement", "class_num": 2, "parent": None, "type": "balance"},
    {"number": "251", "name": "Installations, machines et outillage", "class_num": 2, "parent": "25", "type": "balance"},
    {"number": "252", "name": "Mobilier et matériel roulant", "class_num": 2, "parent": "25", "type": "balance"},
    {"number": "26", "name": "Autres immobilisations corporelles", "class_num": 2, "parent": None, "type": "balance"},
    {"number": "28", "name": "Cautionnements versés", "class_num": 2, "parent": None, "type": "balance"},
    # Classe 3 - Stocks
    {"number": "311", "name": "Stocks clés", "class_num": 3, "parent": None, "type": "balance"},
    {"number": "312", "name": "Stocks badges", "class_num": 3, "parent": None, "type": "balance"},
    {"number": "313", "name": "Stocks plaquettes", "class_num": 3, "parent": None, "type": "balance"},
    # Classe 4 - Creances et dettes a un an au plus
    {"number": "41", "name": "Créances", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "410", "name": "Copropriétaires", "class_num": 4, "parent": "41", "type": "balance"},
    {"number": "41301", "name": "Contentieux Song", "class_num": 4, "parent": "41", "type": "balance"},
    {"number": "416", "name": "Créances diverses", "class_num": 4, "parent": "41", "type": "balance"},
    {"number": "417", "name": "Créances douteuses", "class_num": 4, "parent": "41", "type": "balance"},
    {"number": "4170", "name": "Avances Abords", "class_num": 4, "parent": "417", "type": "balance"},
    {"number": "418", "name": "Locataires", "class_num": 4, "parent": "41", "type": "balance"},
    {"number": "419", "name": "Réductions de valeur actées", "class_num": 4, "parent": "41", "type": "balance"},
    {"number": "42", "name": "Dettes à plus d'un an échéant dans l'année", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "420", "name": "Emprunts subordonnés", "class_num": 4, "parent": "42", "type": "balance"},
    {"number": "421", "name": "Emprunts obligataires non subordonnés", "class_num": 4, "parent": "42", "type": "balance"},
    {"number": "422", "name": "Dettes de location-financement et assimilées", "class_num": 4, "parent": "42", "type": "balance"},
    {"number": "423", "name": "Etablissements de crédit", "class_num": 4, "parent": "42", "type": "balance"},
    {"number": "424", "name": "Autres emprunts", "class_num": 4, "parent": "42", "type": "balance"},
    {"number": "425", "name": "Dettes commerciales", "class_num": 4, "parent": "42", "type": "balance"},
    {"number": "429", "name": "Dettes diverses", "class_num": 4, "parent": "42", "type": "balance"},
    {"number": "43", "name": "Dettes financières", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "430", "name": "Etablissements de crédit - Emprunts en compte à terme fixe", "class_num": 4, "parent": "43", "type": "balance"},
    {"number": "431", "name": "Etablissements de crédit - Promesses", "class_num": 4, "parent": "43", "type": "balance"},
    {"number": "432", "name": "Etablissements de crédit - Crédits d'acceptation", "class_num": 4, "parent": "43", "type": "balance"},
    {"number": "433", "name": "Etablissements de crédit - Dettes en compte courant", "class_num": 4, "parent": "43", "type": "balance"},
    {"number": "439", "name": "Autres emprunts", "class_num": 4, "parent": "43", "type": "balance"},
    {"number": "44", "name": "Dettes commerciales", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "440", "name": "Fournisseurs", "class_num": 4, "parent": "44", "type": "balance"},
    {"number": "444", "name": "Factures à recevoir", "class_num": 4, "parent": "44", "type": "balance"},
    {"number": "45", "name": "Dettes fiscales, salariales et sociales", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "450", "name": "Dettes fiscales estimées", "class_num": 4, "parent": "45", "type": "balance"},
    {"number": "452", "name": "Impôts et taxes à payer", "class_num": 4, "parent": "45", "type": "balance"},
    {"number": "453", "name": "Précomptes retenus", "class_num": 4, "parent": "45", "type": "balance"},
    {"number": "454", "name": "Office national de la sécurité sociale", "class_num": 4, "parent": "45", "type": "balance"},
    {"number": "455", "name": "Rémunérations", "class_num": 4, "parent": "45", "type": "balance"},
    {"number": "456", "name": "Pécules de vacances", "class_num": 4, "parent": "45", "type": "balance"},
    {"number": "459", "name": "Autres dettes sociales", "class_num": 4, "parent": "45", "type": "balance"},
    {"number": "4601", "name": "Dépenses des abords", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "48", "name": "Dettes diverses", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "481", "name": "Compte intermédiaire de mensualisation", "class_num": 4, "parent": "48", "type": "balance"},
    {"number": "489", "name": "Dettes : valeurs reportées", "class_num": 4, "parent": "48", "type": "balance"},
    {"number": "49", "name": "Comptes de régularisation", "class_num": 4, "parent": None, "type": "balance"},
    {"number": "490", "name": "Charges à reporter", "class_num": 4, "parent": "49", "type": "balance"},
    {"number": "491", "name": "Produits acquis", "class_num": 4, "parent": "49", "type": "balance"},
    {"number": "492", "name": "Charges à imputer", "class_num": 4, "parent": "49", "type": "balance"},
    {"number": "493", "name": "Produits à reporter", "class_num": 4, "parent": "49", "type": "balance"},
    {"number": "494", "name": "Compte de régularisation", "class_num": 4, "parent": "49", "type": "balance"},
    {"number": "499", "name": "Divers", "class_num": 4, "parent": "49", "type": "balance"},
    {"number": "4991", "name": "Arrondis débiteurs", "class_num": 4, "parent": "499", "type": "balance"},
    {"number": "4992", "name": "Arrondis créditeurs", "class_num": 4, "parent": "499", "type": "balance"},
    {"number": "4993", "name": "Comptes d'attente débiteur", "class_num": 4, "parent": "499", "type": "balance"},
    {"number": "4994", "name": "Compte d'attente créditeur", "class_num": 4, "parent": "499", "type": "balance"},
    {"number": "4995", "name": "Charges et produits à régulariser", "class_num": 4, "parent": "499", "type": "balance"},
    {"number": "4996", "name": "Frais couverts par les assurances", "class_num": 4, "parent": "499", "type": "balance"},
    {"number": "499601", "name": "Sinistre inondations 07/2021", "class_num": 4, "parent": "4996", "type": "balance"},
    {"number": "499602", "name": "Sinistre DDE - Appartement 32", "class_num": 4, "parent": "4996", "type": "balance"},
    {"number": "499603", "name": "Sinistre heurt porte garage", "class_num": 4, "parent": "4996", "type": "balance"},
    {"number": "499604", "name": "Sinistre juridique Song", "class_num": 4, "parent": "4996", "type": "balance"},
    {"number": "499605", "name": "Sinisitre infiltration Bombay (I4)// Hendrick (I3)", "class_num": 4, "parent": "4996", "type": "balance"},
    {"number": "499606", "name": "Sinistre perte de pression chaudière", "class_num": 4, "parent": "4996", "type": "balance"},
    # Classe 5 - Tresorerie
    {"number": "53", "name": "Dépôts à terme", "class_num": 5, "parent": None, "type": "balance"},
    {"number": "530", "name": "Dépôts à terme de plus d'un an", "class_num": 5, "parent": "53", "type": "balance"},
    {"number": "531", "name": "Dépôts à terme de plus d'un mois et à un an au plus", "class_num": 5, "parent": "53", "type": "balance"},
    {"number": "532", "name": "Dépôts à terme d'un mois au plus", "class_num": 5, "parent": "53", "type": "balance"},
    {"number": "539", "name": "Réductions de valeur actées", "class_num": 5, "parent": "53", "type": "balance"},
    {"number": "55", "name": "Etablissements de crédit", "class_num": 5, "parent": None, "type": "balance"},
    {"number": "550", "name": "Compte vue Réserve", "class_num": 5, "parent": "55", "type": "balance"},
    {"number": "5500591", "name": "Compte réserve", "class_num": 5, "parent": "550", "type": "balance"},
    {"number": "550396", "name": "Compte épargne (BNP - 396)", "class_num": 5, "parent": "550", "type": "balance"},
    {"number": "551", "name": "Compte vue Roulement", "class_num": 5, "parent": "55", "type": "balance"},
    {"number": "551079", "name": "Compte à vue (BNP-079)", "class_num": 5, "parent": "551", "type": "balance"},
    {"number": "551249", "name": "Compte à vue ING", "class_num": 5, "parent": "551", "type": "balance"},
    {"number": "552", "name": "Autres comptes", "class_num": 5, "parent": "55", "type": "balance"},
    {"number": "57", "name": "Caisses", "class_num": 5, "parent": None, "type": "balance"},
    {"number": "58", "name": "Virements internes", "class_num": 5, "parent": None, "type": "balance"},
    # Classe 6 - Charges
    {"number": "61", "name": "Services et biens divers", "class_num": 6, "parent": None, "type": "result"},
    {"number": "610", "name": "Entretien et petites réparations de bâtiment, jardin et environs", "class_num": 6, "parent": "61", "type": "result"},
    {"number": "6100", "name": "Protection anti-incendie", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61000", "name": "Contrats d'entretien", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "61001", "name": "Extincteurs d'incendie", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "61002", "name": "Collecteurs d'incendie", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "61003", "name": "Lutte anti-incendie autres", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "61004", "name": "Alerte incendie et détection incendie", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "61005", "name": "Prévention incendie", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "61006", "name": "Entretien escaliers de secours/voies d'évacuation/coupoles d'évacuation de fumée", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "61007", "name": "Signalisation de sécurité/éclairage de secours", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "61008", "name": "Protection contre la foudre", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "61009", "name": "Autres", "class_num": 6, "parent": "6100", "type": "result"},
    {"number": "6101", "name": "Ascenseurs", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61010", "name": "Contrôle ascenseurs", "class_num": 6, "parent": "6101", "type": "result"},
    {"number": "61011", "name": "Contrat d'entretien ascenseurs", "class_num": 6, "parent": "6101", "type": "result"},
    {"number": "61012", "name": "Entretien et réparations ascenseurs non compris dans contrat d'entretien", "class_num": 6, "parent": "6101", "type": "result"},
    {"number": "61013", "name": "Téléphone d'urgence ascenseurs", "class_num": 6, "parent": "6101", "type": "result"},
    {"number": "61014", "name": "Travaux d'adaptation ascenseurs", "class_num": 6, "parent": "6101", "type": "result"},
    {"number": "61015", "name": "Autres charges ascenseurs", "class_num": 6, "parent": "6101", "type": "result"},
    {"number": "6102", "name": "Installations électriques", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61020", "name": "Contrôle installations électriques", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "61021", "name": "Contrats d'entretien", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "61022", "name": "Autre entretien installations électriques", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "61023", "name": "Entretien sonnettes et parlophones/vidéophones", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "61024", "name": "Rénovation installations électriques", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "61025", "name": "Groupes auxiliaires", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "61026", "name": "Air conditionné et traitement de l'air", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "61027", "name": "Extracteurs d'air et de fumée", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "61028", "name": "Vidéosurveillance", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "61029", "name": "Autres", "class_num": 6, "parent": "6102", "type": "result"},
    {"number": "6103", "name": "Sanitaires et chauffage", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61030", "name": "Contrôle des installations", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "61031", "name": "Contrats d'entretien", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "61032", "name": "Autre entretien installations de chauffage", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "61033", "name": "Autre entretien surpresseur d'eau", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "61034", "name": "Autre entretien adoucisseur d'eau et traitement de l'eau", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "61035", "name": "Autre entretien conduites de chauffage", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "61036", "name": "Autre entretien conduites d'eau", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "61037", "name": "Autre entretien évacuation, égouts et installations de pompage", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "61038", "name": "Compteurs et relevé des compteurs", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "61039", "name": "Autres", "class_num": 6, "parent": "6103", "type": "result"},
    {"number": "6104", "name": "Menuiseries", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61040", "name": "Contrats d'entretien", "class_num": 6, "parent": "6104", "type": "result"},
    {"number": "61041", "name": "Entretien porte de garage", "class_num": 6, "parent": "6104", "type": "result"},
    {"number": "61042", "name": "Entretien menuiseries externes", "class_num": 6, "parent": "6104", "type": "result"},
    {"number": "61043", "name": "Entretien menuiseries internes", "class_num": 6, "parent": "6104", "type": "result"},
    {"number": "61044", "name": "Balustrades et cloisons de séparation des terrasses", "class_num": 6, "parent": "6104", "type": "result"},
    {"number": "61045", "name": "Autres", "class_num": 6, "parent": "6104", "type": "result"},
    {"number": "6105", "name": "Nettoyage et traitement des ordures ménagères", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61050", "name": "Nettoyage bâtiment selon contrat", "class_num": 6, "parent": "6105", "type": "result"},
    {"number": "61051", "name": "Nettoyage bâtiment autres", "class_num": 6, "parent": "6105", "type": "result"},
    {"number": "61052", "name": "Produits d'entretien nettoyage", "class_num": 6, "parent": "6105", "type": "result"},
    {"number": "61053", "name": "Matériel nettoyage", "class_num": 6, "parent": "6105", "type": "result"},
    {"number": "61054", "name": "Ordures ménagères/PMC/papier et verre selon contrat", "class_num": 6, "parent": "6105", "type": "result"},
    {"number": "610541", "name": "Traitement des déchets Moloks", "class_num": 6, "parent": "61054", "type": "result"},
    {"number": "610542", "name": "Frais de gestion des Moloks", "class_num": 6, "parent": "61054", "type": "result"},
    {"number": "610543", "name": "Frais de location Moloks", "class_num": 6, "parent": "61054", "type": "result"},
    {"number": "610544", "name": "Frais de gestion de Moloks (Innovim)", "class_num": 6, "parent": "61054", "type": "result"},
    {"number": "61055", "name": "Ordures ménagères/PMC/papier et verre autres", "class_num": 6, "parent": "6105", "type": "result"},
    {"number": "61056", "name": "Produits ordures ménagères/PMC/papier et verre", "class_num": 6, "parent": "6105", "type": "result"},
    {"number": "61057", "name": "Contrôles", "class_num": 6, "parent": "6105", "type": "result"},
    {"number": "61058", "name": "Autres", "class_num": 6, "parent": "6105", "type": "result"},
    {"number": "6106", "name": "Jardins, parkings et chemins", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61060", "name": "Entretien jardins et environs immédiats selon contrat", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "61061", "name": "Autre entretien jardins et environs immédiats", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "61062", "name": "Aménagement jardins et environs immédiats", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "61063", "name": "Entretien parkings, chemins et environs immédiats selon contrat", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "61064", "name": "Autre entretien parkings, chemins et environs immédiats", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "61065", "name": "Travaux de rénovation parkings, chemins et environs immédiats", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "61066", "name": "Travaux divers", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "61067", "name": "Travaux abords", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "61068", "name": "Imputation des charges abords", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "61069", "name": "Répartition des travaux divers ACP Abords", "class_num": 6, "parent": "6106", "type": "result"},
    {"number": "6107", "name": "Entretien bâtiments", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61070", "name": "Entretien fondations", "class_num": 6, "parent": "6107", "type": "result"},
    {"number": "61071", "name": "Entretien façades", "class_num": 6, "parent": "6107", "type": "result"},
    {"number": "61072", "name": "Entretien terrasses", "class_num": 6, "parent": "6107", "type": "result"},
    {"number": "61073", "name": "Entretien toits", "class_num": 6, "parent": "6107", "type": "result"},
    {"number": "61074", "name": "Entretien cheminées et canaux de ventilation", "class_num": 6, "parent": "6107", "type": "result"},
    {"number": "61075", "name": "Entretien caves", "class_num": 6, "parent": "6107", "type": "result"},
    {"number": "61076", "name": "Travaux d'entretien hall, cages d'escaliers, couloirs", "class_num": 6, "parent": "6107", "type": "result"},
    {"number": "6108", "name": "Piscine", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61080", "name": "Contrôles", "class_num": 6, "parent": "6108", "type": "result"},
    {"number": "61081", "name": "Contrat d'entretien", "class_num": 6, "parent": "6108", "type": "result"},
    {"number": "61082", "name": "Autre entretien piscine/installations techniques", "class_num": 6, "parent": "6108", "type": "result"},
    {"number": "61083", "name": "Fourniture produits", "class_num": 6, "parent": "6108", "type": "result"},
    {"number": "61084", "name": "Surveillance", "class_num": 6, "parent": "6108", "type": "result"},
    {"number": "61085", "name": "Réparations piscine/installations techniques", "class_num": 6, "parent": "6108", "type": "result"},
    {"number": "61086", "name": "Autres", "class_num": 6, "parent": "6108", "type": "result"},
    {"number": "6109", "name": "Divers", "class_num": 6, "parent": "610", "type": "result"},
    {"number": "61090", "name": "Contrats d'entretien", "class_num": 6, "parent": "6109", "type": "result"},
    {"number": "61091", "name": "Charges blanchisserie", "class_num": 6, "parent": "6109", "type": "result"},
    {"number": "61092", "name": "Charges récréatives (plaines de jeux, tennis, fitness, billard,...)", "class_num": 6, "parent": "6109", "type": "result"},
    {"number": "61093", "name": "Contrôle et surveillance", "class_num": 6, "parent": "6109", "type": "result"},
    {"number": "611", "name": "Travaux de rénovation et autres travaux exceptionnels", "class_num": 6, "parent": "61", "type": "result"},
    {"number": "6110", "name": "Frais d'études et surveillance", "class_num": 6, "parent": "611", "type": "result"},
    {"number": "6111", "name": "Rénovation", "class_num": 6, "parent": "611", "type": "result"},
    {"number": "6112", "name": "Travaux de transformation", "class_num": 6, "parent": "611", "type": "result"},
    {"number": "6113", "name": "Travaux d'extension", "class_num": 6, "parent": "611", "type": "result"},
    {"number": "612", "name": "Fournitures à l'association", "class_num": 6, "parent": "61", "type": "result"},
    {"number": "6120", "name": "Eau", "class_num": 6, "parent": "612", "type": "result"},
    {"number": "61200", "name": "Redevance fixe et consommation", "class_num": 6, "parent": "6120", "type": "result"},
    {"number": "61201", "name": "Eau parties communes", "class_num": 6, "parent": "6120", "type": "result"},
    {"number": "61202", "name": "Sel pour adoucisseur d'eau", "class_num": 6, "parent": "6120", "type": "result"},
    {"number": "61203", "name": "Autres fournitures pour adoucisseur d'eau", "class_num": 6, "parent": "6120", "type": "result"},
    {"number": "61204", "name": "Fournitures pour traitement de l'eau", "class_num": 6, "parent": "6120", "type": "result"},
    {"number": "61205", "name": "Autres", "class_num": 6, "parent": "6120", "type": "result"},
    {"number": "61206", "name": "Consommation eau selon relevé", "class_num": 6, "parent": "6120", "type": "result"},
    {"number": "6121", "name": "Electricité", "class_num": 6, "parent": "612", "type": "result"},
    {"number": "61210", "name": "Electricité parties communes", "class_num": 6, "parent": "6121", "type": "result"},
    {"number": "61211", "name": "Electricité ascenseurs", "class_num": 6, "parent": "6121", "type": "result"},
    {"number": "61212", "name": "Electricité chauffage et sanitaires", "class_num": 6, "parent": "6121", "type": "result"},
    {"number": "61213", "name": "Autres", "class_num": 6, "parent": "6121", "type": "result"},
    {"number": "61214", "name": "Electricité commun 55A commun (0663)", "class_num": 6, "parent": "6121", "type": "result"},
    {"number": "61215", "name": "Electricité ascenseur 55-B (1974)", "class_num": 6, "parent": "6121", "type": "result"},
    {"number": "61216", "name": "Electricité commun 53A commun (3377)", "class_num": 6, "parent": "6121", "type": "result"},
    {"number": "61217", "name": "Electricité ascenseur 53-B (6083)", "class_num": 6, "parent": "6121", "type": "result"},
    {"number": "61218", "name": "Electricité commun 55A commun (0663)", "class_num": 6, "parent": "6121", "type": "result"},
    {"number": "6122", "name": "Gaz", "class_num": 6, "parent": "612", "type": "result"},
    {"number": "61220", "name": "Redevance fixe et consommation", "class_num": 6, "parent": "6122", "type": "result"},
    {"number": "61221", "name": "Autres", "class_num": 6, "parent": "6122", "type": "result"},
    {"number": "6123", "name": "Mazout", "class_num": 6, "parent": "612", "type": "result"},
    {"number": "61230", "name": "Contrôles cuves", "class_num": 6, "parent": "6123", "type": "result"},
    {"number": "61231", "name": "Entretiens cuves", "class_num": 6, "parent": "6123", "type": "result"},
    {"number": "61232", "name": "Livraisons mazout", "class_num": 6, "parent": "6123", "type": "result"},
    {"number": "6124", "name": "Autres services collectifs", "class_num": 6, "parent": "612", "type": "result"},
    {"number": "61240", "name": "Câblodistribution", "class_num": 6, "parent": "6124", "type": "result"},
    {"number": "6125", "name": "Autres fournitures", "class_num": 6, "parent": "612", "type": "result"},
    {"number": "613", "name": "Honoraires, charges membres du conseil et charges commissaire interne aux comptes", "class_num": 6, "parent": "61", "type": "result"},
    {"number": "6130", "name": "Honoraires", "class_num": 6, "parent": "613", "type": "result"},
    {"number": "61300", "name": "Honoraires syndics", "class_num": 6, "parent": "6130", "type": "result"},
    {"number": "61301", "name": "Honoraires avocats", "class_num": 6, "parent": "6130", "type": "result"},
    {"number": "61302", "name": "Honoraires architectes/ingénieurs", "class_num": 6, "parent": "6130", "type": "result"},
    {"number": "61303", "name": "Honoraires experts", "class_num": 6, "parent": "6130", "type": "result"},
    {"number": "61304", "name": "Honoraires commissaire externe aux comptes", "class_num": 6, "parent": "6130", "type": "result"},
    {"number": "61305", "name": "Autres honoraires", "class_num": 6, "parent": "6130", "type": "result"},
    {"number": "6131", "name": "Charges membres du conseil (conseil de copropriété) et commissaire interne aux comptes", "class_num": 6, "parent": "613", "type": "result"},
    {"number": "61310", "name": "Indemnités membres du conseil interne et commissaire interne aux comptes", "class_num": 6, "parent": "6131", "type": "result"},
    {"number": "61311", "name": "Frais de déplacement membres du conseil interne et commissaire interne aux comptes", "class_num": 6, "parent": "6131", "type": "result"},
    {"number": "61312", "name": "Autres charges conseil de copropriété", "class_num": 6, "parent": "6131", "type": "result"},
    {"number": "614", "name": "Assurances", "class_num": 6, "parent": "61", "type": "result"},
    {"number": "6140", "name": "Assurance incendie", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "6141", "name": "Responsabilité civile", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "6142", "name": "Assurance accidents du travail", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "6143", "name": "Assurance volontaires", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "6144", "name": "Assurance membres du conseil interne et commissaire aux comptes", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "6145", "name": "Responsabilité professionnelle syndic non professionnel", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "6146", "name": "Assistance judiciaire", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "6147", "name": "Franchise", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "6148", "name": "Autres", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "6149", "name": "Assurance protection juridique", "class_num": 6, "parent": "614", "type": "result"},
    {"number": "615", "name": "Conciergerie", "class_num": 6, "parent": "61", "type": "result"},
    {"number": "6150", "name": "Téléphone - Internet - gsm", "class_num": 6, "parent": "615", "type": "result"},
    {"number": "6151", "name": "Electricité", "class_num": 6, "parent": "615", "type": "result"},
    {"number": "6152", "name": "Eau", "class_num": 6, "parent": "615", "type": "result"},
    {"number": "6153", "name": "Gaz", "class_num": 6, "parent": "615", "type": "result"},
    {"number": "6154", "name": "Chauffage", "class_num": 6, "parent": "615", "type": "result"},
    {"number": "6155", "name": "Télédistribution", "class_num": 6, "parent": "615", "type": "result"},
    {"number": "6156", "name": "Charges", "class_num": 6, "parent": "615", "type": "result"},
    {"number": "6157", "name": "Entretien", "class_num": 6, "parent": "615", "type": "result"},
    {"number": "6158", "name": "Autres", "class_num": 6, "parent": "615", "type": "result"},
    {"number": "616", "name": "Frais d'administration et de gestion", "class_num": 6, "parent": "61", "type": "result"},
    {"number": "6160", "name": "Frais d'administration syndic", "class_num": 6, "parent": "616", "type": "result"},
    {"number": "61600", "name": "Bureau et matériel de bureau", "class_num": 6, "parent": "6160", "type": "result"},
    {"number": "61601", "name": "Timbres", "class_num": 6, "parent": "6160", "type": "result"},
    {"number": "61602", "name": "Téléphone", "class_num": 6, "parent": "6160", "type": "result"},
    {"number": "61603", "name": "Autres", "class_num": 6, "parent": "6160", "type": "result"},
    {"number": "6161", "name": "Frais réunions", "class_num": 6, "parent": "616", "type": "result"},
    {"number": "61610", "name": "Utilisation salles de réunion", "class_num": 6, "parent": "6161", "type": "result"},
    {"number": "61611", "name": "Consommations réunions", "class_num": 6, "parent": "6161", "type": "result"},
    {"number": "61612", "name": "Autres", "class_num": 6, "parent": "6161", "type": "result"},
    {"number": "6162", "name": "Traductions", "class_num": 6, "parent": "616", "type": "result"},
    {"number": "61620", "name": "Traduction simultanée réunions", "class_num": 6, "parent": "6162", "type": "result"},
    {"number": "61621", "name": "Traduction documents", "class_num": 6, "parent": "6162", "type": "result"},
    {"number": "6163", "name": "Frais de procédure", "class_num": 6, "parent": "616", "type": "result"},
    {"number": "61630", "name": "Frais de procédure recouvrement arriérés copropriétaires", "class_num": 6, "parent": "6163", "type": "result"},
    {"number": "61631", "name": "Autres frais de procédure", "class_num": 6, "parent": "6163", "type": "result"},
    {"number": "6164", "name": "Publications et modification des statuts", "class_num": 6, "parent": "616", "type": "result"},
    {"number": "61640", "name": "Publication nomination syndic", "class_num": 6, "parent": "6164", "type": "result"},
    {"number": "61641", "name": "Modification des statuts", "class_num": 6, "parent": "6164", "type": "result"},
    {"number": "6165", "name": "Frais transfert de propriété", "class_num": 6, "parent": "616", "type": "result"},
    {"number": "61650", "name": "Attestations article 577-11 Code civil", "class_num": 6, "parent": "6165", "type": "result"},
    {"number": "61651", "name": "Autres", "class_num": 6, "parent": "6165", "type": "result"},
    {"number": "6166", "name": "Frais divers gestion", "class_num": 6, "parent": "616", "type": "result"},
    {"number": "61660", "name": "Communication d'informations sur Internet", "class_num": 6, "parent": "6166", "type": "result"},
    {"number": "61661", "name": "Frais d'accession à la propriété", "class_num": 6, "parent": "6166", "type": "result"},
    {"number": "61662", "name": "Frais archives", "class_num": 6, "parent": "6166", "type": "result"},
    {"number": "61663", "name": "Autres frais gestion", "class_num": 6, "parent": "6166", "type": "result"},
    {"number": "62", "name": "Rémunérations, charges sociales et pensions", "class_num": 6, "parent": None, "type": "result"},
    {"number": "620", "name": "Rémunérations et avantages sociaux directs", "class_num": 6, "parent": "62", "type": "result"},
    {"number": "621", "name": "Cotisations patronales pour assurances sociales", "class_num": 6, "parent": "62", "type": "result"},
    {"number": "622", "name": "Primes patronales pour assurances extralégales", "class_num": 6, "parent": "62", "type": "result"},
    {"number": "623", "name": "Autres frais de personnel", "class_num": 6, "parent": "62", "type": "result"},
    {"number": "624", "name": "Pensions de retraite et de survie", "class_num": 6, "parent": "62", "type": "result"},
    {"number": "63", "name": "Amortissements et réductions de valeur", "class_num": 6, "parent": None, "type": "result"},
    {"number": "630", "name": "Dotations aux amortissements sur immobilisations", "class_num": 6, "parent": "63", "type": "result"},
    {"number": "6301", "name": "Dotations aux amortissements sur immobilisations incorporelles", "class_num": 6, "parent": "630", "type": "result"},
    {"number": "6302", "name": "Dotations aux amortissements sur immobilisations corporelles", "class_num": 6, "parent": "630", "type": "result"},
    {"number": "634", "name": "Réductions de valeur sur créances à un an au plus", "class_num": 6, "parent": "63", "type": "result"},
    {"number": "6340", "name": "Dotations", "class_num": 6, "parent": "634", "type": "result"},
    {"number": "6341", "name": "Reprises", "class_num": 6, "parent": "634", "type": "result"},
    {"number": "64", "name": "Autres charges", "class_num": 6, "parent": None, "type": "result"},
    {"number": "640", "name": "Taxes et redevances", "class_num": 6, "parent": "64", "type": "result"},
    {"number": "641", "name": "Moins-values sur la réalisation des créances", "class_num": 6, "parent": "64", "type": "result"},
    {"number": "642", "name": "Charges diverses", "class_num": 6, "parent": "64", "type": "result"},
    {"number": "643", "name": "Frais privatifs", "class_num": 6, "parent": "64", "type": "result"},
    {"number": "65", "name": "Charges financières", "class_num": 6, "parent": None, "type": "result"},
    {"number": "650", "name": "Frais bancaires et charges des dettes", "class_num": 6, "parent": "65", "type": "result"},
    {"number": "657", "name": "Charges financières diverses", "class_num": 6, "parent": "65", "type": "result"},
    {"number": "66", "name": "Charges exceptionnelles", "class_num": 6, "parent": None, "type": "result"},
    {"number": "671", "name": "Charges travaux extraordinaires", "class_num": 6, "parent": None, "type": "result"},
    {"number": "69", "name": "Valeurs à reporter", "class_num": 6, "parent": None, "type": "result"},
    {"number": "693", "name": "Valeurs à reporter", "class_num": 6, "parent": "69", "type": "result"},
    # Classe 7 - Produits
    {"number": "70", "name": "Acomptes", "class_num": 7, "parent": None, "type": "result"},
    {"number": "700", "name": "Acomptes fonds de réserve", "class_num": 7, "parent": "70", "type": "result"},
    {"number": "701", "name": "Provisions", "class_num": 7, "parent": "70", "type": "result"},
    {"number": "702", "name": "Provisions extraordinaires", "class_num": 7, "parent": "70", "type": "result"},
    {"number": "742", "name": "Recettes loyers", "class_num": 7, "parent": None, "type": "result"},
    {"number": "75", "name": "Produits financiers", "class_num": 7, "parent": None, "type": "result"},
    {"number": "750", "name": "Intérêts créditeurs", "class_num": 7, "parent": "75", "type": "result"},
    {"number": "76", "name": "Produits exceptionnels", "class_num": 7, "parent": None, "type": "result"},
    {"number": "76001", "name": "Indemnité emménagement / déménagement", "class_num": 7, "parent": "76", "type": "result"},
]


# ---------------------------------------------------------------------------
# Comptes de compatibilite (master legacy) - garantissent que les automatismes
# (tier_accounts 40000XXX/40010XXX/44000XXX, banques 550xxx/551xxx, fallback
# auto-entries 614000/615000/700000/701000) restent fonctionnels.
# Ces comptes sont seedes a la creation d'une ACP mais peuvent etre desactives.
# ---------------------------------------------------------------------------
PCMN_COMPAT_ACCOUNTS = [
    {"number": "400000", "name": "Coproprietaires - Master provisions", "class_num": 4, "parent": "410", "type": "balance"},
    {"number": "400100", "name": "Coproprietaires - Master fonds de reserve", "class_num": 4, "parent": "410", "type": "balance"},
    {"number": "440000", "name": "Fournisseurs - Master", "class_num": 4, "parent": "440", "type": "balance"},
    {"number": "550000", "name": "Banque - Compte courant (compat)", "class_num": 5, "parent": "550", "type": "balance"},
    {"number": "550100", "name": "Banque - Compte epargne (compat)", "class_num": 5, "parent": "550", "type": "balance"},
    {"number": "550200", "name": "Banque - Fonds de reserve (compat)", "class_num": 5, "parent": "550", "type": "balance"},
    {"number": "614000", "name": "Honoraires syndic (synthese)", "class_num": 6, "parent": "6130", "type": "result"},
    {"number": "615000", "name": "Frais de gestion (synthese)", "class_num": 6, "parent": "616", "type": "result"},
    {"number": "700000", "name": "Provisions pour charges communes (synthese)", "class_num": 7, "parent": "70", "type": "result"},
    {"number": "701000", "name": "Provisions fonds de reserve (synthese)", "class_num": 7, "parent": "701", "type": "result"},
]

# Le seed complet utilise par l'application (327 + 10 compat = 337 comptes)
PCMN_ALL_ACCOUNTS = PCMN_ACCOUNTS + PCMN_COMPAT_ACCOUNTS

